// Generated by dedot cli

import type {
  GenericSubstrateApi,
  RpcLegacy,
  RpcV2,
  RpcVersion,
} from "dedot/types";
import { ChainConsts } from "./consts.d.ts";
import { ChainStorage } from "./query.d.ts";
import { ChainJsonRpcApis } from "./json-rpc.d.ts";
import { ChainErrors } from "./errors.d.ts";
import { ChainEvents } from "./events.d.ts";
import { RuntimeApis } from "./runtime.d.ts";
import { ChainViewFunctions } from "./view-functions.d.ts";
import { ChainTx } from "./tx.d.ts";

export * from "./types.d.ts";

export interface VersionedCharli3SubstrateRuntimeApi<Rv extends RpcVersion>
  extends GenericSubstrateApi<Rv> {
  rpc: ChainJsonRpcApis<Rv>;
  consts: ChainConsts<Rv>;
  query: ChainStorage<Rv>;
  errors: ChainErrors<Rv>;
  events: ChainEvents<Rv>;
  call: RuntimeApis<Rv>;
  view: ChainViewFunctions<Rv>;
  tx: ChainTx<Rv>;
}

/**
 * @name: Charli3SubstrateRuntimeApi
 * @specVersion: 100
 */
export interface Charli3SubstrateRuntimeApi {
  legacy: VersionedCharli3SubstrateRuntimeApi<RpcLegacy>;
  v2: VersionedCharli3SubstrateRuntimeApi<RpcV2>;
}
