// Generated by dedot cli

import type { GenericRuntimeApis, GenericRuntimeApiMethod } from 'dedot/types';
import type {
  Result,
  BytesLike,
  Bytes,
  RuntimeVersion,
  Header,
  DispatchError,
  UncheckedExtrinsicLike,
  UncheckedExtrinsic,
  H256,
  AccountId32Like,
} from 'dedot/codecs';
import type {
  SpRuntimeBlock,
  SpRuntimeExtrinsicInclusionMode,
  SpCoreOpaqueMetadata,
  SpRuntimeTransactionValidityTransactionValidityError,
  SpInherentsInherentData,
  SpInherentsCheckInherentsResult,
  SpRuntimeTransactionValidityValidTransaction,
  SpRuntimeTransactionValidityTransactionSource,
  SpConsensusSlotsSlotDuration,
  SpConsensusAuraEd25519AppEd25519Public,
  SpCoreCryptoKeyTypeId,
  SpConsensusGrandpaAppPublic,
  SpConsensusGrandpaEquivocationProof,
  SpRuntimeOpaqueValue,
  PalletTransactionPaymentRuntimeDispatchInfo,
  PalletTransactionPaymentFeeDetails,
  SpWeightsWeightV2Weight,
  SidechainRuntimeRuntimeCallLike,
  SidechainDomainUtxoId,
  SpSidechainSidechainStatus,
  SidechainSlotsScSlotConfig,
  SpSessionValidatorManagementMainChainScripts,
  SidechainDomainScEpochNumber,
  SidechainRuntimeOpaqueCrossChainAppPublic,
  SidechainRuntimeOpaqueSessionKeys,
  AuthoritySelectionInherentsAuthoritySelectionInputs,
  AuthoritySelectionInherentsFilterInvalidCandidatesRegistrationDataError,
  SidechainDomainMainchainPublicKey,
  SidechainDomainRegistrationData,
  AuthoritySelectionInherentsFilterInvalidCandidatesStakeError,
  SidechainDomainStakeDelegation,
  AuthoritySelectionInherentsFilterInvalidCandidatesPermissionedCandidateDataError,
  SidechainDomainPermissionedCandidateData,
  SpNativeTokenManagementMainChainScripts,
} from './types.js';

export interface RuntimeApis extends GenericRuntimeApis {
  /**
   * @runtimeapi: GenesisBuilder - 0xfbc577b9d747efd6
   **/
  genesisBuilder: {
    /**
     * Build `RuntimeGenesisConfig` from a JSON blob not using any defaults and store it in the
     * storage.
     *
     * In the case of a FRAME-based runtime, this function deserializes the full
     * `RuntimeGenesisConfig` from the given JSON blob and puts it into the storage. If the
     * provided JSON blob is incorrect or incomplete or the deserialization fails, an error
     * is returned.
     *
     * Please note that provided JSON blob must contain all `RuntimeGenesisConfig` fields, no
     * defaults will be used.
     *
     * @callname: GenesisBuilder_build_state
     * @param {BytesLike} json
     **/
    buildState: GenericRuntimeApiMethod<(json: BytesLike) => Promise<Result<[], string>>>;

    /**
     * Returns a JSON blob representation of the built-in `RuntimeGenesisConfig` identified by
     * `id`.
     *
     * If `id` is `None` the function should return JSON blob representation of the default
     * `RuntimeGenesisConfig` struct of the runtime. Implementation must provide default
     * `RuntimeGenesisConfig`.
     *
     * Otherwise function returns a JSON representation of the built-in, named
     * `RuntimeGenesisConfig` preset identified by `id`, or `None` if such preset does not
     * exist. Returned `Vec<u8>` contains bytes of JSON blob (patch) which comprises a list of
     * (potentially nested) key-value pairs that are intended for customizing the default
     * runtime genesis config. The patch shall be merged (rfc7386) with the JSON representation
     * of the default `RuntimeGenesisConfig` to create a comprehensive genesis config that can
     * be used in `build_state` method.
     *
     * @callname: GenesisBuilder_get_preset
     * @param {string | undefined} id
     **/
    getPreset: GenericRuntimeApiMethod<(id?: string | undefined) => Promise<Bytes | undefined>>;

    /**
     * Returns a list of identifiers for available builtin `RuntimeGenesisConfig` presets.
     *
     * The presets from the list can be queried with [`GenesisBuilder::get_preset`] method. If
     * no named presets are provided by the runtime the list is empty.
     *
     * @callname: GenesisBuilder_preset_names
     **/
    presetNames: GenericRuntimeApiMethod<() => Promise<Array<string>>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: Core - 0xdf6acb689907609b
   **/
  core: {
    /**
     * Returns the version of the runtime.
     *
     * @callname: Core_version
     **/
    version: GenericRuntimeApiMethod<() => Promise<RuntimeVersion>>;

    /**
     * Execute the given block.
     *
     * @callname: Core_execute_block
     * @param {SpRuntimeBlock} block
     **/
    executeBlock: GenericRuntimeApiMethod<(block: SpRuntimeBlock) => Promise<[]>>;

    /**
     * Initialize a block with the given header and return the runtime executive mode.
     *
     * @callname: Core_initialize_block
     * @param {Header} header
     **/
    initializeBlock: GenericRuntimeApiMethod<
      (header: Header) => Promise<SpRuntimeExtrinsicInclusionMode>
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: Metadata - 0x37e397fc7c91f5e4
   **/
  metadata: {
    /**
     * Returns the metadata of a runtime.
     *
     * @callname: Metadata_metadata
     **/
    metadata: GenericRuntimeApiMethod<() => Promise<SpCoreOpaqueMetadata>>;

    /**
     * Returns the metadata at a given version.
     *
     * If the given `version` isn't supported, this will return `None`.
     * Use [`Self::metadata_versions`] to find out about supported metadata version of the runtime.
     *
     * @callname: Metadata_metadata_at_version
     * @param {number} version
     **/
    metadataAtVersion: GenericRuntimeApiMethod<
      (version: number) => Promise<SpCoreOpaqueMetadata | undefined>
    >;

    /**
     * Returns the supported metadata versions.
     *
     * This can be used to call `metadata_at_version`.
     *
     * @callname: Metadata_metadata_versions
     **/
    metadataVersions: GenericRuntimeApiMethod<() => Promise<Array<number>>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: BlockBuilder - 0x40fe3ad401f8959a
   **/
  blockBuilder: {
    /**
     * Apply the given extrinsic.
     *
     * Returns an inclusion outcome which specifies if this extrinsic is included in
     * this block or not.
     *
     * @callname: BlockBuilder_apply_extrinsic
     * @param {UncheckedExtrinsicLike} extrinsic
     **/
    applyExtrinsic: GenericRuntimeApiMethod<
      (
        extrinsic: UncheckedExtrinsicLike,
      ) => Promise<
        Result<Result<[], DispatchError>, SpRuntimeTransactionValidityTransactionValidityError>
      >
    >;

    /**
     * Finish the current block.
     *
     * @callname: BlockBuilder_finalize_block
     **/
    finalizeBlock: GenericRuntimeApiMethod<() => Promise<Header>>;

    /**
     * Generate inherent extrinsics. The inherent data will vary from chain to chain.
     *
     * @callname: BlockBuilder_inherent_extrinsics
     * @param {SpInherentsInherentData} inherent
     **/
    inherentExtrinsics: GenericRuntimeApiMethod<
      (inherent: SpInherentsInherentData) => Promise<Array<UncheckedExtrinsic>>
    >;

    /**
     * Check that the inherents are valid. The inherent data will vary from chain to chain.
     *
     * @callname: BlockBuilder_check_inherents
     * @param {SpRuntimeBlock} block
     * @param {SpInherentsInherentData} data
     **/
    checkInherents: GenericRuntimeApiMethod<
      (
        block: SpRuntimeBlock,
        data: SpInherentsInherentData,
      ) => Promise<SpInherentsCheckInherentsResult>
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: TaggedTransactionQueue - 0xd2bc9897eed08f15
   **/
  taggedTransactionQueue: {
    /**
     * Validate the transaction.
     *
     * This method is invoked by the transaction pool to learn details about given transaction.
     * The implementation should make sure to verify the correctness of the transaction
     * against current state. The given `block_hash` corresponds to the hash of the block
     * that is used as current state.
     *
     * Note that this call may be performed by the pool multiple times and transactions
     * might be verified in any possible order.
     *
     * @callname: TaggedTransactionQueue_validate_transaction
     * @param {SpRuntimeTransactionValidityTransactionSource} source
     * @param {UncheckedExtrinsicLike} tx
     * @param {H256} block_hash
     **/
    validateTransaction: GenericRuntimeApiMethod<
      (
        source: SpRuntimeTransactionValidityTransactionSource,
        tx: UncheckedExtrinsicLike,
        blockHash: H256,
      ) => Promise<
        Result<
          SpRuntimeTransactionValidityValidTransaction,
          SpRuntimeTransactionValidityTransactionValidityError
        >
      >
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: OffchainWorkerApi - 0xf78b278be53f454c
   **/
  offchainWorkerApi: {
    /**
     * Starts the off-chain task for given block header.
     *
     * @callname: OffchainWorkerApi_offchain_worker
     * @param {Header} header
     **/
    offchainWorker: GenericRuntimeApiMethod<(header: Header) => Promise<[]>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: AuraApi - 0xdd718d5cc53262d4
   **/
  auraApi: {
    /**
     * Returns the slot duration for Aura.
     *
     * Currently, only the value provided by this type at genesis will be used.
     *
     * @callname: AuraApi_slot_duration
     **/
    slotDuration: GenericRuntimeApiMethod<() => Promise<SpConsensusSlotsSlotDuration>>;

    /**
     * Return the current set of authorities.
     *
     * @callname: AuraApi_authorities
     **/
    authorities: GenericRuntimeApiMethod<
      () => Promise<Array<SpConsensusAuraEd25519AppEd25519Public>>
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: SessionKeys - 0xab3c0572291feb8b
   **/
  sessionKeys: {
    /**
     * Generate a set of session keys with optionally using the given seed.
     * The keys should be stored within the keystore exposed via runtime
     * externalities.
     *
     * The seed needs to be a valid `utf8` string.
     *
     * Returns the concatenated SCALE encoded public keys.
     *
     * @callname: SessionKeys_generate_session_keys
     * @param {BytesLike | undefined} seed
     **/
    generateSessionKeys: GenericRuntimeApiMethod<(seed?: BytesLike | undefined) => Promise<Bytes>>;

    /**
     * Decode the given public session keys.
     *
     * Returns the list of public raw public keys + key type.
     *
     * @callname: SessionKeys_decode_session_keys
     * @param {BytesLike} encoded
     **/
    decodeSessionKeys: GenericRuntimeApiMethod<
      (encoded: BytesLike) => Promise<Array<[Bytes, SpCoreCryptoKeyTypeId]> | undefined>
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: GrandpaApi - 0xed99c5acb25eedf5
   **/
  grandpaApi: {
    /**
     * Get the current GRANDPA authorities and weights. This should not change except
     * for when changes are scheduled and the corresponding delay has passed.
     *
     * When called at block B, it will return the set of authorities that should be
     * used to finalize descendants of this block (B+1, B+2, ...). The block B itself
     * is finalized by the authorities from block B-1.
     *
     * @callname: GrandpaApi_grandpa_authorities
     **/
    grandpaAuthorities: GenericRuntimeApiMethod<
      () => Promise<Array<[SpConsensusGrandpaAppPublic, bigint]>>
    >;

    /**
     * Submits an unsigned extrinsic to report an equivocation. The caller
     * must provide the equivocation proof and a key ownership proof
     * (should be obtained using `generate_key_ownership_proof`). The
     * extrinsic will be unsigned and should only be accepted for local
     * authorship (not to be broadcast to the network). This method returns
     * `None` when creation of the extrinsic fails, e.g. if equivocation
     * reporting is disabled for the given runtime (i.e. this method is
     * hardcoded to return `None`). Only useful in an offchain context.
     *
     * @callname: GrandpaApi_submit_report_equivocation_unsigned_extrinsic
     * @param {SpConsensusGrandpaEquivocationProof} equivocation_proof
     * @param {SpRuntimeOpaqueValue} key_owner_proof
     **/
    submitReportEquivocationUnsignedExtrinsic: GenericRuntimeApiMethod<
      (
        equivocationProof: SpConsensusGrandpaEquivocationProof,
        keyOwnerProof: SpRuntimeOpaqueValue,
      ) => Promise<[] | undefined>
    >;

    /**
     * Generates a proof of key ownership for the given authority in the
     * given set. An example usage of this module is coupled with the
     * session historical module to prove that a given authority key is
     * tied to a given staking identity during a specific session. Proofs
     * of key ownership are necessary for submitting equivocation reports.
     * NOTE: even though the API takes a `set_id` as parameter the current
     * implementations ignore this parameter and instead rely on this
     * method being called at the correct block height, i.e. any point at
     * which the given set id is live on-chain. Future implementations will
     * instead use indexed data through an offchain worker, not requiring
     * older states to be available.
     *
     * @callname: GrandpaApi_generate_key_ownership_proof
     * @param {bigint} set_id
     * @param {SpConsensusGrandpaAppPublic} authority_id
     **/
    generateKeyOwnershipProof: GenericRuntimeApiMethod<
      (
        setId: bigint,
        authorityId: SpConsensusGrandpaAppPublic,
      ) => Promise<SpRuntimeOpaqueValue | undefined>
    >;

    /**
     * Get current GRANDPA authority set id.
     *
     * @callname: GrandpaApi_current_set_id
     **/
    currentSetId: GenericRuntimeApiMethod<() => Promise<bigint>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: AccountNonceApi - 0xbc9d89904f5b923f
   **/
  accountNonceApi: {
    /**
     * Get current account nonce of given `AccountId`.
     *
     * @callname: AccountNonceApi_account_nonce
     * @param {AccountId32Like} account
     **/
    accountNonce: GenericRuntimeApiMethod<(account: AccountId32Like) => Promise<number>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: TransactionPaymentApi - 0x37c8bb1350a9a2a8
   **/
  transactionPaymentApi: {
    /**
     *
     * @callname: TransactionPaymentApi_query_info
     * @param {UncheckedExtrinsicLike} uxt
     * @param {number} len
     **/
    queryInfo: GenericRuntimeApiMethod<
      (
        uxt: UncheckedExtrinsicLike,
        len: number,
      ) => Promise<PalletTransactionPaymentRuntimeDispatchInfo>
    >;

    /**
     *
     * @callname: TransactionPaymentApi_query_fee_details
     * @param {UncheckedExtrinsicLike} uxt
     * @param {number} len
     **/
    queryFeeDetails: GenericRuntimeApiMethod<
      (uxt: UncheckedExtrinsicLike, len: number) => Promise<PalletTransactionPaymentFeeDetails>
    >;

    /**
     *
     * @callname: TransactionPaymentApi_query_weight_to_fee
     * @param {SpWeightsWeightV2Weight} weight
     **/
    queryWeightToFee: GenericRuntimeApiMethod<(weight: SpWeightsWeightV2Weight) => Promise<bigint>>;

    /**
     *
     * @callname: TransactionPaymentApi_query_length_to_fee
     * @param {number} length
     **/
    queryLengthToFee: GenericRuntimeApiMethod<(length: number) => Promise<bigint>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: TransactionPaymentCallApi - 0xf3ff14d5ab527059
   **/
  transactionPaymentCallApi: {
    /**
     * Query information of a dispatch class, weight, and fee of a given encoded `Call`.
     *
     * @callname: TransactionPaymentCallApi_query_call_info
     * @param {SidechainRuntimeRuntimeCallLike} call
     * @param {number} len
     **/
    queryCallInfo: GenericRuntimeApiMethod<
      (
        call: SidechainRuntimeRuntimeCallLike,
        len: number,
      ) => Promise<PalletTransactionPaymentRuntimeDispatchInfo>
    >;

    /**
     * Query fee details of a given encoded `Call`.
     *
     * @callname: TransactionPaymentCallApi_query_call_fee_details
     * @param {SidechainRuntimeRuntimeCallLike} call
     * @param {number} len
     **/
    queryCallFeeDetails: GenericRuntimeApiMethod<
      (
        call: SidechainRuntimeRuntimeCallLike,
        len: number,
      ) => Promise<PalletTransactionPaymentFeeDetails>
    >;

    /**
     * Query the output of the current `WeightToFee` given some input.
     *
     * @callname: TransactionPaymentCallApi_query_weight_to_fee
     * @param {SpWeightsWeightV2Weight} weight
     **/
    queryWeightToFee: GenericRuntimeApiMethod<(weight: SpWeightsWeightV2Weight) => Promise<bigint>>;

    /**
     * Query the output of the current `LengthToFee` given some input.
     *
     * @callname: TransactionPaymentCallApi_query_length_to_fee
     * @param {number} length
     **/
    queryLengthToFee: GenericRuntimeApiMethod<(length: number) => Promise<bigint>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: GetGenesisUtxo - 0xd9bc84ac3bfb8a0c
   **/
  getGenesisUtxo: {
    /**
     *
     * @callname: GetGenesisUtxo_genesis_utxo
     **/
    genesisUtxo: GenericRuntimeApiMethod<() => Promise<SidechainDomainUtxoId>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: GetSidechainStatus - 0xa0c89371ec56244c
   **/
  getSidechainStatus: {
    /**
     *
     * @callname: GetSidechainStatus_get_sidechain_status
     **/
    getSidechainStatus: GenericRuntimeApiMethod<() => Promise<SpSidechainSidechainStatus>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: SlotApi - 0xc7805fd5ec973a86
   **/
  slotApi: {
    /**
     *
     * @callname: SlotApi_slot_config
     **/
    slotConfig: GenericRuntimeApiMethod<() => Promise<SidechainSlotsScSlotConfig>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: SessionValidatorManagementApi - 0x19dba14093498f16
   **/
  sessionValidatorManagementApi: {
    /**
     *
     * @callname: SessionValidatorManagementApi_get_main_chain_scripts
     **/
    getMainChainScripts: GenericRuntimeApiMethod<
      () => Promise<SpSessionValidatorManagementMainChainScripts>
    >;

    /**
     *
     * @callname: SessionValidatorManagementApi_get_current_committee
     **/
    getCurrentCommittee: GenericRuntimeApiMethod<
      () => Promise<
        [SidechainDomainScEpochNumber, Array<SidechainRuntimeOpaqueCrossChainAppPublic>]
      >
    >;

    /**
     *
     * @callname: SessionValidatorManagementApi_get_next_committee
     **/
    getNextCommittee: GenericRuntimeApiMethod<
      () => Promise<
        [SidechainDomainScEpochNumber, Array<SidechainRuntimeOpaqueCrossChainAppPublic>] | undefined
      >
    >;

    /**
     *
     * @callname: SessionValidatorManagementApi_get_next_unset_epoch_number
     **/
    getNextUnsetEpochNumber: GenericRuntimeApiMethod<() => Promise<SidechainDomainScEpochNumber>>;

    /**
     *
     * @callname: SessionValidatorManagementApi_calculate_committee
     * @param {AuthoritySelectionInherentsAuthoritySelectionInputs} authority_selection_inputs
     * @param {SidechainDomainScEpochNumber} sidechain_epoch
     **/
    calculateCommittee: GenericRuntimeApiMethod<
      (
        authoritySelectionInputs: AuthoritySelectionInherentsAuthoritySelectionInputs,
        sidechainEpoch: SidechainDomainScEpochNumber,
      ) => Promise<
        | Array<[SidechainRuntimeOpaqueCrossChainAppPublic, SidechainRuntimeOpaqueSessionKeys]>
        | undefined
      >
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: CandidateValidationApi - 0x279a32908e96410d
   **/
  candidateValidationApi: {
    /**
     *
     * @callname: CandidateValidationApi_validate_registered_candidate_data
     * @param {SidechainDomainMainchainPublicKey} mainchain_pub_key
     * @param {SidechainDomainRegistrationData} registration_data
     **/
    validateRegisteredCandidateData: GenericRuntimeApiMethod<
      (
        mainchainPubKey: SidechainDomainMainchainPublicKey,
        registrationData: SidechainDomainRegistrationData,
      ) => Promise<
        AuthoritySelectionInherentsFilterInvalidCandidatesRegistrationDataError | undefined
      >
    >;

    /**
     *
     * @callname: CandidateValidationApi_validate_stake
     * @param {SidechainDomainStakeDelegation | undefined} stake
     **/
    validateStake: GenericRuntimeApiMethod<
      (
        stake?: SidechainDomainStakeDelegation | undefined,
      ) => Promise<AuthoritySelectionInherentsFilterInvalidCandidatesStakeError | undefined>
    >;

    /**
     *
     * @callname: CandidateValidationApi_validate_permissioned_candidate_data
     * @param {SidechainDomainPermissionedCandidateData} candidate
     **/
    validatePermissionedCandidateData: GenericRuntimeApiMethod<
      (
        candidate: SidechainDomainPermissionedCandidateData,
      ) => Promise<
        AuthoritySelectionInherentsFilterInvalidCandidatesPermissionedCandidateDataError | undefined
      >
    >;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
  /**
   * @runtimeapi: NativeTokenManagementApi - 0x7e7a86948600f49b
   **/
  nativeTokenManagementApi: {
    /**
     *
     * @callname: NativeTokenManagementApi_get_main_chain_scripts
     **/
    getMainChainScripts: GenericRuntimeApiMethod<
      () => Promise<SpNativeTokenManagementMainChainScripts | undefined>
    >;

    /**
     * Gets current initializaion status and set it to `true` afterwards. This check is used to
     * determine whether historical data from the beginning of main chain should be queried.
     *
     * @callname: NativeTokenManagementApi_initialized
     **/
    initialized: GenericRuntimeApiMethod<() => Promise<boolean>>;

    /**
     * Generic runtime api call
     **/
    [method: string]: GenericRuntimeApiMethod;
  };
}
