// Generated by dedot cli

import type {
  GenericChainTx,
  GenericTxCall,
  GenericChainKnownTypes,
  ISubmittableExtrinsic,
  ISubmittableResult,
  IRuntimeTxCall,
} from 'dedot/types';
import type {
  MultiAddressLike,
  Extrinsic,
  BytesLike,
  H256,
  AccountId32Like,
  FixedBytes,
} from 'dedot/codecs';
import type {
  SidechainRuntimeRuntimeCallLike,
  SpRuntimeMultiSignature,
  FrameSystemEventRecord,
  SpConsensusGrandpaEquivocationProof,
  SpCoreVoid,
  PalletBalancesAdjustmentDirection,
  SpWeightsWeightV2Weight,
  PalletMultisigTimepoint,
  SidechainRuntimeOpaqueCrossChainAppPublic,
  SidechainRuntimeOpaqueSessionKeys,
  SidechainDomainScEpochNumber,
  SidechainDomainMainchainAddress,
  SidechainDomainPolicyId,
  SidechainDomainByteStringSizedByteString,
  SidechainDomainNativeTokenAmount,
  SidechainDomainAssetName,
  Charli3OracleCoreConfigNodeTradePair,
  Charli3OracleCorePalletOracleMessage,
  Charli3OracleCoreConfigNodeConsensusConfiguration,
  Charli3OracleCoreConfigNodeRewardConfiguration,
  Charli3OracleCorePalletSlashVote,
} from './types.js';

export type ChainSubmittableExtrinsic<
  T extends IRuntimeTxCall = SidechainRuntimeRuntimeCallLike,
  ChainKnownTypes extends GenericChainKnownTypes = GenericChainKnownTypes,
> = Extrinsic<MultiAddressLike, T, SpRuntimeMultiSignature, ChainKnownTypes['Extra']> &
  ISubmittableExtrinsic<ISubmittableResult<FrameSystemEventRecord>, ChainKnownTypes['AssetId']>;

export type TxCall<ChainKnownTypes extends GenericChainKnownTypes = GenericChainKnownTypes> = (
  ...args: any[]
) => ChainSubmittableExtrinsic<SidechainRuntimeRuntimeCallLike, ChainKnownTypes>;

export interface ChainTx<
  ChainKnownTypes extends GenericChainKnownTypes = GenericChainKnownTypes,
> extends GenericChainTx<TxCall<ChainKnownTypes>> {
  /**
   * Pallet `System`'s transaction calls
   **/
  system: {
    /**
     * Make some on-chain remark.
     *
     * Can be executed by every `origin`.
     *
     * @param {BytesLike} remark
     **/
    remark: GenericTxCall<
      (remark: BytesLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'Remark';
            params: { remark: BytesLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Set the number of pages in the WebAssembly environment's heap.
     *
     * @param {bigint} pages
     **/
    setHeapPages: GenericTxCall<
      (pages: bigint) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'SetHeapPages';
            params: { pages: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Set the new runtime code.
     *
     * @param {BytesLike} code
     **/
    setCode: GenericTxCall<
      (code: BytesLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'SetCode';
            params: { code: BytesLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Set the new runtime code without doing any checks of the given `code`.
     *
     * Note that runtime upgrades will not run if this is called with a not-increasing spec
     * version!
     *
     * @param {BytesLike} code
     **/
    setCodeWithoutChecks: GenericTxCall<
      (code: BytesLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'SetCodeWithoutChecks';
            params: { code: BytesLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Set some items of storage.
     *
     * @param {Array<[BytesLike, BytesLike]>} items
     **/
    setStorage: GenericTxCall<
      (items: Array<[BytesLike, BytesLike]>) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'SetStorage';
            params: { items: Array<[BytesLike, BytesLike]> };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Kill some items from storage.
     *
     * @param {Array<BytesLike>} keys
     **/
    killStorage: GenericTxCall<
      (keys: Array<BytesLike>) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'KillStorage';
            params: { keys: Array<BytesLike> };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Kill all storage items with a key that starts with the given prefix.
     *
     * **NOTE:** We rely on the Root origin to provide us the number of subkeys under
     * the prefix we are removing to accurately calculate the weight of this function.
     *
     * @param {BytesLike} prefix
     * @param {number} subkeys
     **/
    killPrefix: GenericTxCall<
      (
        prefix: BytesLike,
        subkeys: number,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'KillPrefix';
            params: { prefix: BytesLike; subkeys: number };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Make some on-chain remark and emit event.
     *
     * @param {BytesLike} remark
     **/
    remarkWithEvent: GenericTxCall<
      (remark: BytesLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'RemarkWithEvent';
            params: { remark: BytesLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Authorize an upgrade to a given `code_hash` for the runtime. The runtime can be supplied
     * later.
     *
     * This call requires Root origin.
     *
     * @param {H256} codeHash
     **/
    authorizeUpgrade: GenericTxCall<
      (codeHash: H256) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'AuthorizeUpgrade';
            params: { codeHash: H256 };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Authorize an upgrade to a given `code_hash` for the runtime. The runtime can be supplied
     * later.
     *
     * WARNING: This authorizes an upgrade that will take place without any safety checks, for
     * example that the spec name remains the same and that the version number increases. Not
     * recommended for normal use. Use `authorize_upgrade` instead.
     *
     * This call requires Root origin.
     *
     * @param {H256} codeHash
     **/
    authorizeUpgradeWithoutChecks: GenericTxCall<
      (codeHash: H256) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'AuthorizeUpgradeWithoutChecks';
            params: { codeHash: H256 };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Provide the preimage (runtime binary) `code` for an upgrade that has been authorized.
     *
     * If the authorization required a version check, this call will ensure the spec name
     * remains unchanged and that the spec version has increased.
     *
     * Depending on the runtime's `OnSetCode` configuration, this function may directly apply
     * the new `code` in the same block or attempt to schedule the upgrade.
     *
     * All origins are allowed.
     *
     * @param {BytesLike} code
     **/
    applyAuthorizedUpgrade: GenericTxCall<
      (code: BytesLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'System';
          palletCall: {
            name: 'ApplyAuthorizedUpgrade';
            params: { code: BytesLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Timestamp`'s transaction calls
   **/
  timestamp: {
    /**
     * Set the current time.
     *
     * This call should be invoked exactly once per block. It will panic at the finalization
     * phase, if this call hasn't been invoked by that time.
     *
     * The timestamp should be greater than the previous one by the amount specified by
     * [`Config::MinimumPeriod`].
     *
     * The dispatch origin for this call must be _None_.
     *
     * This dispatch class is _Mandatory_ to ensure it gets executed in the block. Be aware
     * that changing the complexity of this call could result exhausting the resources in a
     * block to execute any other calls.
     *
     * ## Complexity
     * - `O(1)` (Note that implementations of `OnTimestampSet` must also be `O(1)`)
     * - 1 storage read and 1 storage mutation (codec `O(1)` because of `DidUpdate::take` in
     * `on_finalize`)
     * - 1 event handler `on_timestamp_set`. Must be `O(1)`.
     *
     * @param {bigint} now
     **/
    set: GenericTxCall<
      (now: bigint) => ChainSubmittableExtrinsic<
        {
          pallet: 'Timestamp';
          palletCall: {
            name: 'Set';
            params: { now: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Grandpa`'s transaction calls
   **/
  grandpa: {
    /**
     * Report voter equivocation/misbehavior. This method will verify the
     * equivocation proof and validate the given key ownership proof
     * against the extracted offender. If both are valid, the offence
     * will be reported.
     *
     * @param {SpConsensusGrandpaEquivocationProof} equivocationProof
     * @param {SpCoreVoid} keyOwnerProof
     **/
    reportEquivocation: GenericTxCall<
      (
        equivocationProof: SpConsensusGrandpaEquivocationProof,
        keyOwnerProof: SpCoreVoid,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Grandpa';
          palletCall: {
            name: 'ReportEquivocation';
            params: {
              equivocationProof: SpConsensusGrandpaEquivocationProof;
              keyOwnerProof: SpCoreVoid;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Report voter equivocation/misbehavior. This method will verify the
     * equivocation proof and validate the given key ownership proof
     * against the extracted offender. If both are valid, the offence
     * will be reported.
     *
     * This extrinsic must be called unsigned and it is expected that only
     * block authors will call it (validated in `ValidateUnsigned`), as such
     * if the block author is defined it will be defined as the equivocation
     * reporter.
     *
     * @param {SpConsensusGrandpaEquivocationProof} equivocationProof
     * @param {SpCoreVoid} keyOwnerProof
     **/
    reportEquivocationUnsigned: GenericTxCall<
      (
        equivocationProof: SpConsensusGrandpaEquivocationProof,
        keyOwnerProof: SpCoreVoid,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Grandpa';
          palletCall: {
            name: 'ReportEquivocationUnsigned';
            params: {
              equivocationProof: SpConsensusGrandpaEquivocationProof;
              keyOwnerProof: SpCoreVoid;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Note that the current authority set of the GRANDPA finality gadget has stalled.
     *
     * This will trigger a forced authority set change at the beginning of the next session, to
     * be enacted `delay` blocks after that. The `delay` should be high enough to safely assume
     * that the block signalling the forced change will not be re-orged e.g. 1000 blocks.
     * The block production rate (which may be slowed down because of finality lagging) should
     * be taken into account when choosing the `delay`. The GRANDPA voters based on the new
     * authority will start voting on top of `best_finalized_block_number` for new finalized
     * blocks. `best_finalized_block_number` should be the highest of the latest finalized
     * block of all validators of the new authority set.
     *
     * Only callable by root.
     *
     * @param {number} delay
     * @param {number} bestFinalizedBlockNumber
     **/
    noteStalled: GenericTxCall<
      (
        delay: number,
        bestFinalizedBlockNumber: number,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Grandpa';
          palletCall: {
            name: 'NoteStalled';
            params: { delay: number; bestFinalizedBlockNumber: number };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Balances`'s transaction calls
   **/
  balances: {
    /**
     * Transfer some liquid free balance to another account.
     *
     * `transfer_allow_death` will set the `FreeBalance` of the sender and receiver.
     * If the sender's account is below the existential deposit as a result
     * of the transfer, the account will be reaped.
     *
     * The dispatch origin for this call must be `Signed` by the transactor.
     *
     * @param {MultiAddressLike} dest
     * @param {bigint} value
     **/
    transferAllowDeath: GenericTxCall<
      (
        dest: MultiAddressLike,
        value: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'TransferAllowDeath';
            params: { dest: MultiAddressLike; value: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Exactly as `transfer_allow_death`, except the origin must be root and the source account
     * may be specified.
     *
     * @param {MultiAddressLike} source
     * @param {MultiAddressLike} dest
     * @param {bigint} value
     **/
    forceTransfer: GenericTxCall<
      (
        source: MultiAddressLike,
        dest: MultiAddressLike,
        value: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'ForceTransfer';
            params: {
              source: MultiAddressLike;
              dest: MultiAddressLike;
              value: bigint;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Same as the [`transfer_allow_death`] call, but with a check that the transfer will not
     * kill the origin account.
     *
     * 99% of the time you want [`transfer_allow_death`] instead.
     *
     * [`transfer_allow_death`]: struct.Pallet.html#method.transfer
     *
     * @param {MultiAddressLike} dest
     * @param {bigint} value
     **/
    transferKeepAlive: GenericTxCall<
      (
        dest: MultiAddressLike,
        value: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'TransferKeepAlive';
            params: { dest: MultiAddressLike; value: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Transfer the entire transferable balance from the caller account.
     *
     * NOTE: This function only attempts to transfer _transferable_ balances. This means that
     * any locked, reserved, or existential deposits (when `keep_alive` is `true`), will not be
     * transferred by this function. To ensure that this function results in a killed account,
     * you might need to prepare the account by removing any reference counters, storage
     * deposits, etc...
     *
     * The dispatch origin of this call must be Signed.
     *
     * - `dest`: The recipient of the transfer.
     * - `keep_alive`: A boolean to determine if the `transfer_all` operation should send all
     * of the funds the account has, causing the sender account to be killed (false), or
     * transfer everything except at least the existential deposit, which will guarantee to
     * keep the sender account alive (true).
     *
     * @param {MultiAddressLike} dest
     * @param {boolean} keepAlive
     **/
    transferAll: GenericTxCall<
      (
        dest: MultiAddressLike,
        keepAlive: boolean,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'TransferAll';
            params: { dest: MultiAddressLike; keepAlive: boolean };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Unreserve some balance from a user by force.
     *
     * Can only be called by ROOT.
     *
     * @param {MultiAddressLike} who
     * @param {bigint} amount
     **/
    forceUnreserve: GenericTxCall<
      (
        who: MultiAddressLike,
        amount: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'ForceUnreserve';
            params: { who: MultiAddressLike; amount: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Upgrade a specified account.
     *
     * - `origin`: Must be `Signed`.
     * - `who`: The account to be upgraded.
     *
     * This will waive the transaction fee if at least all but 10% of the accounts needed to
     * be upgraded. (We let some not have to be upgraded just in order to allow for the
     * possibility of churn).
     *
     * @param {Array<AccountId32Like>} who
     **/
    upgradeAccounts: GenericTxCall<
      (who: Array<AccountId32Like>) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'UpgradeAccounts';
            params: { who: Array<AccountId32Like> };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Set the regular balance of a given account.
     *
     * The dispatch origin for this call is `root`.
     *
     * @param {MultiAddressLike} who
     * @param {bigint} newFree
     **/
    forceSetBalance: GenericTxCall<
      (
        who: MultiAddressLike,
        newFree: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'ForceSetBalance';
            params: { who: MultiAddressLike; newFree: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Adjust the total issuance in a saturating way.
     *
     * Can only be called by root and always needs a positive `delta`.
     *
     * # Example
     *
     * @param {PalletBalancesAdjustmentDirection} direction
     * @param {bigint} delta
     **/
    forceAdjustTotalIssuance: GenericTxCall<
      (
        direction: PalletBalancesAdjustmentDirection,
        delta: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'ForceAdjustTotalIssuance';
            params: {
              direction: PalletBalancesAdjustmentDirection;
              delta: bigint;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Burn the specified liquid free balance from the origin account.
     *
     * If the origin's account ends up below the existential deposit as a result
     * of the burn and `keep_alive` is false, the account will be reaped.
     *
     * Unlike sending funds to a _burn_ address, which merely makes the funds inaccessible,
     * this `burn` operation will reduce total issuance by the amount _burned_.
     *
     * @param {bigint} value
     * @param {boolean} keepAlive
     **/
    burn: GenericTxCall<
      (
        value: bigint,
        keepAlive: boolean,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Balances';
          palletCall: {
            name: 'Burn';
            params: { value: bigint; keepAlive: boolean };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Sudo`'s transaction calls
   **/
  sudo: {
    /**
     * Authenticates the sudo key and dispatches a function call with `Root` origin.
     *
     * @param {SidechainRuntimeRuntimeCallLike} call
     **/
    sudo: GenericTxCall<
      (call: SidechainRuntimeRuntimeCallLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'Sudo';
          palletCall: {
            name: 'Sudo';
            params: { call: SidechainRuntimeRuntimeCallLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Authenticates the sudo key and dispatches a function call with `Root` origin.
     * This function does not check the weight of the call, and instead allows the
     * Sudo user to specify the weight of the call.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * @param {SidechainRuntimeRuntimeCallLike} call
     * @param {SpWeightsWeightV2Weight} weight
     **/
    sudoUncheckedWeight: GenericTxCall<
      (
        call: SidechainRuntimeRuntimeCallLike,
        weight: SpWeightsWeightV2Weight,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Sudo';
          palletCall: {
            name: 'SudoUncheckedWeight';
            params: {
              call: SidechainRuntimeRuntimeCallLike;
              weight: SpWeightsWeightV2Weight;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Authenticates the current sudo key and sets the given AccountId (`new`) as the new sudo
     * key.
     *
     * @param {MultiAddressLike} new_
     **/
    setKey: GenericTxCall<
      (new_: MultiAddressLike) => ChainSubmittableExtrinsic<
        {
          pallet: 'Sudo';
          palletCall: {
            name: 'SetKey';
            params: { new: MultiAddressLike };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Authenticates the sudo key and dispatches a function call with `Signed` origin from
     * a given account.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * @param {MultiAddressLike} who
     * @param {SidechainRuntimeRuntimeCallLike} call
     **/
    sudoAs: GenericTxCall<
      (
        who: MultiAddressLike,
        call: SidechainRuntimeRuntimeCallLike,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Sudo';
          palletCall: {
            name: 'SudoAs';
            params: {
              who: MultiAddressLike;
              call: SidechainRuntimeRuntimeCallLike;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Permanently removes the sudo key.
     *
     * **This cannot be un-done.**
     *
     **/
    removeKey: GenericTxCall<
      () => ChainSubmittableExtrinsic<
        {
          pallet: 'Sudo';
          palletCall: {
            name: 'RemoveKey';
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Multisig`'s transaction calls
   **/
  multisig: {
    /**
     * Immediately dispatch a multi-signature call using a single approval from the caller.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * - `other_signatories`: The accounts (other than the sender) who are part of the
     * multi-signature, but do not participate in the approval process.
     * - `call`: The call to be executed.
     *
     * Result is equivalent to the dispatched result.
     *
     * ## Complexity
     * O(Z + C) where Z is the length of the call and C its execution weight.
     *
     * @param {Array<AccountId32Like>} otherSignatories
     * @param {SidechainRuntimeRuntimeCallLike} call
     **/
    asMultiThreshold1: GenericTxCall<
      (
        otherSignatories: Array<AccountId32Like>,
        call: SidechainRuntimeRuntimeCallLike,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Multisig';
          palletCall: {
            name: 'AsMultiThreshold1';
            params: {
              otherSignatories: Array<AccountId32Like>;
              call: SidechainRuntimeRuntimeCallLike;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Register approval for a dispatch to be made from a deterministic composite account if
     * approved by a total of `threshold - 1` of `other_signatories`.
     *
     * If there are enough, then dispatch the call.
     *
     * Payment: `DepositBase` will be reserved if this is the first approval, plus
     * `threshold` times `DepositFactor`. It is returned once this dispatch happens or
     * is cancelled.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * - `threshold`: The total number of approvals for this dispatch before it is executed.
     * - `other_signatories`: The accounts (other than the sender) who can approve this
     * dispatch. May not be empty.
     * - `maybe_timepoint`: If this is the first approval, then this must be `None`. If it is
     * not the first approval, then it must be `Some`, with the timepoint (block number and
     * transaction index) of the first approval transaction.
     * - `call`: The call to be executed.
     *
     * NOTE: Unless this is the final approval, you will generally want to use
     * `approve_as_multi` instead, since it only requires a hash of the call.
     *
     * Result is equivalent to the dispatched result if `threshold` is exactly `1`. Otherwise
     * on success, result is `Ok` and the result from the interior call, if it was executed,
     * may be found in the deposited `MultisigExecuted` event.
     *
     * ## Complexity
     * - `O(S + Z + Call)`.
     * - Up to one balance-reserve or unreserve operation.
     * - One passthrough operation, one insert, both `O(S)` where `S` is the number of
     * signatories. `S` is capped by `MaxSignatories`, with weight being proportional.
     * - One call encode & hash, both of complexity `O(Z)` where `Z` is tx-len.
     * - One encode & hash, both of complexity `O(S)`.
     * - Up to one binary search and insert (`O(logS + S)`).
     * - I/O: 1 read `O(S)`, up to 1 mutate `O(S)`. Up to one remove.
     * - One event.
     * - The weight of the `call`.
     * - Storage: inserts one item, value size bounded by `MaxSignatories`, with a deposit
     * taken for its lifetime of `DepositBase + threshold * DepositFactor`.
     *
     * @param {number} threshold
     * @param {Array<AccountId32Like>} otherSignatories
     * @param {PalletMultisigTimepoint | undefined} maybeTimepoint
     * @param {SidechainRuntimeRuntimeCallLike} call
     * @param {SpWeightsWeightV2Weight} maxWeight
     **/
    asMulti: GenericTxCall<
      (
        threshold: number,
        otherSignatories: Array<AccountId32Like>,
        maybeTimepoint: PalletMultisigTimepoint | undefined,
        call: SidechainRuntimeRuntimeCallLike,
        maxWeight: SpWeightsWeightV2Weight,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Multisig';
          palletCall: {
            name: 'AsMulti';
            params: {
              threshold: number;
              otherSignatories: Array<AccountId32Like>;
              maybeTimepoint: PalletMultisigTimepoint | undefined;
              call: SidechainRuntimeRuntimeCallLike;
              maxWeight: SpWeightsWeightV2Weight;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Register approval for a dispatch to be made from a deterministic composite account if
     * approved by a total of `threshold - 1` of `other_signatories`.
     *
     * Payment: `DepositBase` will be reserved if this is the first approval, plus
     * `threshold` times `DepositFactor`. It is returned once this dispatch happens or
     * is cancelled.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * - `threshold`: The total number of approvals for this dispatch before it is executed.
     * - `other_signatories`: The accounts (other than the sender) who can approve this
     * dispatch. May not be empty.
     * - `maybe_timepoint`: If this is the first approval, then this must be `None`. If it is
     * not the first approval, then it must be `Some`, with the timepoint (block number and
     * transaction index) of the first approval transaction.
     * - `call_hash`: The hash of the call to be executed.
     *
     * NOTE: If this is the final approval, you will want to use `as_multi` instead.
     *
     * ## Complexity
     * - `O(S)`.
     * - Up to one balance-reserve or unreserve operation.
     * - One passthrough operation, one insert, both `O(S)` where `S` is the number of
     * signatories. `S` is capped by `MaxSignatories`, with weight being proportional.
     * - One encode & hash, both of complexity `O(S)`.
     * - Up to one binary search and insert (`O(logS + S)`).
     * - I/O: 1 read `O(S)`, up to 1 mutate `O(S)`. Up to one remove.
     * - One event.
     * - Storage: inserts one item, value size bounded by `MaxSignatories`, with a deposit
     * taken for its lifetime of `DepositBase + threshold * DepositFactor`.
     *
     * @param {number} threshold
     * @param {Array<AccountId32Like>} otherSignatories
     * @param {PalletMultisigTimepoint | undefined} maybeTimepoint
     * @param {FixedBytes<32>} callHash
     * @param {SpWeightsWeightV2Weight} maxWeight
     **/
    approveAsMulti: GenericTxCall<
      (
        threshold: number,
        otherSignatories: Array<AccountId32Like>,
        maybeTimepoint: PalletMultisigTimepoint | undefined,
        callHash: FixedBytes<32>,
        maxWeight: SpWeightsWeightV2Weight,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Multisig';
          palletCall: {
            name: 'ApproveAsMulti';
            params: {
              threshold: number;
              otherSignatories: Array<AccountId32Like>;
              maybeTimepoint: PalletMultisigTimepoint | undefined;
              callHash: FixedBytes<32>;
              maxWeight: SpWeightsWeightV2Weight;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Cancel a pre-existing, on-going multisig transaction. Any deposit reserved previously
     * for this operation will be unreserved on success.
     *
     * The dispatch origin for this call must be _Signed_.
     *
     * - `threshold`: The total number of approvals for this dispatch before it is executed.
     * - `other_signatories`: The accounts (other than the sender) who can approve this
     * dispatch. May not be empty.
     * - `timepoint`: The timepoint (block number and transaction index) of the first approval
     * transaction for this dispatch.
     * - `call_hash`: The hash of the call to be executed.
     *
     * ## Complexity
     * - `O(S)`.
     * - Up to one balance-reserve or unreserve operation.
     * - One passthrough operation, one insert, both `O(S)` where `S` is the number of
     * signatories. `S` is capped by `MaxSignatories`, with weight being proportional.
     * - One encode & hash, both of complexity `O(S)`.
     * - One event.
     * - I/O: 1 read `O(S)`, one remove.
     * - Storage: removes one item.
     *
     * @param {number} threshold
     * @param {Array<AccountId32Like>} otherSignatories
     * @param {PalletMultisigTimepoint} timepoint
     * @param {FixedBytes<32>} callHash
     **/
    cancelAsMulti: GenericTxCall<
      (
        threshold: number,
        otherSignatories: Array<AccountId32Like>,
        timepoint: PalletMultisigTimepoint,
        callHash: FixedBytes<32>,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Multisig';
          palletCall: {
            name: 'CancelAsMulti';
            params: {
              threshold: number;
              otherSignatories: Array<AccountId32Like>;
              timepoint: PalletMultisigTimepoint;
              callHash: FixedBytes<32>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Poke the deposit reserved for an existing multisig operation.
     *
     * The dispatch origin for this call must be _Signed_ and must be the original depositor of
     * the multisig operation.
     *
     * The transaction fee is waived if the deposit amount has changed.
     *
     * - `threshold`: The total number of approvals needed for this multisig.
     * - `other_signatories`: The accounts (other than the sender) who are part of the
     * multisig.
     * - `call_hash`: The hash of the call this deposit is reserved for.
     *
     * Emits `DepositPoked` if successful.
     *
     * @param {number} threshold
     * @param {Array<AccountId32Like>} otherSignatories
     * @param {FixedBytes<32>} callHash
     **/
    pokeDeposit: GenericTxCall<
      (
        threshold: number,
        otherSignatories: Array<AccountId32Like>,
        callHash: FixedBytes<32>,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Multisig';
          palletCall: {
            name: 'PokeDeposit';
            params: {
              threshold: number;
              otherSignatories: Array<AccountId32Like>;
              callHash: FixedBytes<32>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `SessionCommitteeManagement`'s transaction calls
   **/
  sessionCommitteeManagement: {
    /**
     * 'for_epoch_number' parameter is needed only for validation purposes, because we need to make sure that
     * check_inherent uses the same epoch_number as was used to create inherent data.
     * Alternative approach would be to put epoch number inside InherentData. However, sidechain
     * epoch number is set in Runtime, thus, inherent data provider doesn't have to know about it.
     * On top of that, the latter approach is slightly more complicated to code.
     *
     * @param {Array<[SidechainRuntimeOpaqueCrossChainAppPublic, SidechainRuntimeOpaqueSessionKeys]>} validators
     * @param {SidechainDomainScEpochNumber} forEpochNumber
     **/
    set: GenericTxCall<
      (
        validators: Array<
          [SidechainRuntimeOpaqueCrossChainAppPublic, SidechainRuntimeOpaqueSessionKeys]
        >,
        forEpochNumber: SidechainDomainScEpochNumber,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'SessionCommitteeManagement';
          palletCall: {
            name: 'Set';
            params: {
              validators: Array<
                [SidechainRuntimeOpaqueCrossChainAppPublic, SidechainRuntimeOpaqueSessionKeys]
              >;
              forEpochNumber: SidechainDomainScEpochNumber;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Changes the main chain scripts used for committee rotation.
     *
     * This extrinsic must be run either using `sudo` or some other chain governance mechanism.
     *
     * @param {SidechainDomainMainchainAddress} committeeCandidateAddress
     * @param {SidechainDomainPolicyId} dParameterPolicyId
     * @param {SidechainDomainPolicyId} permissionedCandidatesPolicyId
     **/
    setMainChainScripts: GenericTxCall<
      (
        committeeCandidateAddress: SidechainDomainMainchainAddress,
        dParameterPolicyId: SidechainDomainPolicyId,
        permissionedCandidatesPolicyId: SidechainDomainPolicyId,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'SessionCommitteeManagement';
          palletCall: {
            name: 'SetMainChainScripts';
            params: {
              committeeCandidateAddress: SidechainDomainMainchainAddress;
              dParameterPolicyId: SidechainDomainPolicyId;
              permissionedCandidatesPolicyId: SidechainDomainPolicyId;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `BlockRewards`'s transaction calls
   **/
  blockRewards: {
    /**
     *
     * @param {SidechainDomainByteStringSizedByteString} beneficiary
     **/
    setCurrentBlockBeneficiary: GenericTxCall<
      (beneficiary: SidechainDomainByteStringSizedByteString) => ChainSubmittableExtrinsic<
        {
          pallet: 'BlockRewards';
          palletCall: {
            name: 'SetCurrentBlockBeneficiary';
            params: { beneficiary: SidechainDomainByteStringSizedByteString };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `PalletSession`'s transaction calls
   **/
  palletSession: {
    /**
     * Sets the session key(s) of the function caller to `keys`.
     * Allows an account to set its session key prior to becoming a validator.
     * This doesn't take effect until the next session.
     *
     * The dispatch origin of this function must be signed.
     *
     * ## Complexity
     * - `O(1)`. Actual cost depends on the number of length of `T::Keys::key_ids()` which is
     * fixed.
     *
     * @param {SidechainRuntimeOpaqueSessionKeys} keys
     * @param {BytesLike} proof
     **/
    setKeys: GenericTxCall<
      (
        keys: SidechainRuntimeOpaqueSessionKeys,
        proof: BytesLike,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'PalletSession';
          palletCall: {
            name: 'SetKeys';
            params: {
              keys: SidechainRuntimeOpaqueSessionKeys;
              proof: BytesLike;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Removes any session key(s) of the function caller.
     *
     * This doesn't take effect until the next session.
     *
     * The dispatch origin of this function must be Signed and the account must be either be
     * convertible to a validator ID using the chain's typical addressing system (this usually
     * means being a controller account) or directly convertible into a validator ID (which
     * usually means being a stash account).
     *
     * ## Complexity
     * - `O(1)` in number of key types. Actual cost depends on the number of length of
     * `T::Keys::key_ids()` which is fixed.
     *
     **/
    purgeKeys: GenericTxCall<
      () => ChainSubmittableExtrinsic<
        {
          pallet: 'PalletSession';
          palletCall: {
            name: 'PurgeKeys';
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `NativeTokenManagement`'s transaction calls
   **/
  nativeTokenManagement: {
    /**
     *
     * @param {SidechainDomainNativeTokenAmount} tokenAmount
     **/
    transferTokens: GenericTxCall<
      (tokenAmount: SidechainDomainNativeTokenAmount) => ChainSubmittableExtrinsic<
        {
          pallet: 'NativeTokenManagement';
          palletCall: {
            name: 'TransferTokens';
            params: { tokenAmount: SidechainDomainNativeTokenAmount };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Changes the main chain scripts used for observing native token transfers.
     *
     * This extrinsic must be run either using `sudo` or some other chain governance mechanism.
     *
     * @param {SidechainDomainPolicyId} nativeTokenPolicyId
     * @param {SidechainDomainAssetName} nativeTokenAssetName
     * @param {SidechainDomainMainchainAddress} illiquidSupplyValidatorAddress
     **/
    setMainChainScripts: GenericTxCall<
      (
        nativeTokenPolicyId: SidechainDomainPolicyId,
        nativeTokenAssetName: SidechainDomainAssetName,
        illiquidSupplyValidatorAddress: SidechainDomainMainchainAddress,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'NativeTokenManagement';
          palletCall: {
            name: 'SetMainChainScripts';
            params: {
              nativeTokenPolicyId: SidechainDomainPolicyId;
              nativeTokenAssetName: SidechainDomainAssetName;
              illiquidSupplyValidatorAddress: SidechainDomainMainchainAddress;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
  /**
   * Pallet `Oracle`'s transaction calls
   **/
  oracle: {
    /**
     *
     * @param {Array<[Charli3OracleCoreConfigNodeTradePair, bigint]>} prices
     **/
    storePrices: GenericTxCall<
      (prices: Array<[Charli3OracleCoreConfigNodeTradePair, bigint]>) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'StorePrices';
            params: {
              prices: Array<[Charli3OracleCoreConfigNodeTradePair, bigint]>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {Array<[Charli3OracleCorePalletOracleMessage, SpRuntimeMultiSignature]>} signatures
     **/
    storeSignatures: GenericTxCall<
      (
        signatures: Array<[Charli3OracleCorePalletOracleMessage, SpRuntimeMultiSignature]>,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'StoreSignatures';
            params: {
              signatures: Array<[Charli3OracleCorePalletOracleMessage, SpRuntimeMultiSignature]>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {Charli3OracleCoreConfigNodeConsensusConfiguration} consensusConfig
     * @param {Array<[BytesLike, Array<number>]>} channelsToTradePairs
     * @param {Charli3OracleCoreConfigNodeRewardConfiguration | undefined} rewardConfig
     **/
    sudoSetConfig: GenericTxCall<
      (
        consensusConfig: Charli3OracleCoreConfigNodeConsensusConfiguration,
        channelsToTradePairs: Array<[BytesLike, Array<number>]>,
        rewardConfig: Charli3OracleCoreConfigNodeRewardConfiguration | undefined,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'SudoSetConfig';
            params: {
              consensusConfig: Charli3OracleCoreConfigNodeConsensusConfiguration;
              channelsToTradePairs: Array<[BytesLike, Array<number>]>;
              rewardConfig: Charli3OracleCoreConfigNodeRewardConfiguration | undefined;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} oracleAccount
     **/
    sudoRegisterOracleNode: GenericTxCall<
      (oracleAccount: AccountId32Like) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'SudoRegisterOracleNode';
            params: { oracleAccount: AccountId32Like };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} oracleAccount
     **/
    sudoDeregisterOracleNode: GenericTxCall<
      (oracleAccount: AccountId32Like) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'SudoDeregisterOracleNode';
            params: { oracleAccount: AccountId32Like };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} nodeAccount
     * @param {bigint} stakeAmount
     * @param {number} lockUntilBlock
     * @param {BytesLike} cardanoPkhAdmin
     * @param {BytesLike} cardanoPkhAggregation
     * @param {FixedBytes<32>} adminPubkey
     * @param {FixedBytes<64>} adminSig
     **/
    generateStakingCertificate: GenericTxCall<
      (
        nodeAccount: AccountId32Like,
        stakeAmount: bigint,
        lockUntilBlock: number,
        cardanoPkhAdmin: BytesLike,
        cardanoPkhAggregation: BytesLike,
        adminPubkey: FixedBytes<32>,
        adminSig: FixedBytes<64>,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'GenerateStakingCertificate';
            params: {
              nodeAccount: AccountId32Like;
              stakeAmount: bigint;
              lockUntilBlock: number;
              cardanoPkhAdmin: BytesLike;
              cardanoPkhAggregation: BytesLike;
              adminPubkey: FixedBytes<32>;
              adminSig: FixedBytes<64>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {FixedBytes<32>} txHash
     **/
    confirmCardanoStake: GenericTxCall<
      (txHash: FixedBytes<32>) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'ConfirmCardanoStake';
            params: { txHash: FixedBytes<32> };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     **/
    requestRetire: GenericTxCall<
      () => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'RequestRetire';
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} nodeAccount
     * @param {number} lockUntilBlock
     * @param {number} expiresAtBlock
     **/
    generateRetireCertificate: GenericTxCall<
      (
        nodeAccount: AccountId32Like,
        lockUntilBlock: number,
        expiresAtBlock: number,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'GenerateRetireCertificate';
            params: {
              nodeAccount: AccountId32Like;
              lockUntilBlock: number;
              expiresAtBlock: number;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} nodeAccount
     * @param {bigint} slashAmount
     **/
    requestSlash: GenericTxCall<
      (
        nodeAccount: AccountId32Like,
        slashAmount: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'RequestSlash';
            params: { nodeAccount: AccountId32Like; slashAmount: bigint };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} nodeAccount
     * @param {Charli3OracleCorePalletSlashVote} vote
     **/
    voteSlash: GenericTxCall<
      (
        nodeAccount: AccountId32Like,
        vote: Charli3OracleCorePalletSlashVote,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'VoteSlash';
            params: {
              nodeAccount: AccountId32Like;
              vote: Charli3OracleCorePalletSlashVote;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {AccountId32Like} nodeAccount
     * @param {bigint} approvedAmount
     * @param {FixedBytes<32>} adminPubkey
     * @param {FixedBytes<64>} adminSig
     **/
    generateWithdrawalCertificate: GenericTxCall<
      (
        nodeAccount: AccountId32Like,
        approvedAmount: bigint,
        adminPubkey: FixedBytes<32>,
        adminSig: FixedBytes<64>,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'GenerateWithdrawalCertificate';
            params: {
              nodeAccount: AccountId32Like;
              approvedAmount: bigint;
              adminPubkey: FixedBytes<32>;
              adminSig: FixedBytes<64>;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     *
     * @param {FixedBytes<32>} txHash
     * @param {bigint} releasedAmount
     * @param {bigint} penaltyAmount
     **/
    confirmCardanoWithdrawal: GenericTxCall<
      (
        txHash: FixedBytes<32>,
        releasedAmount: bigint,
        penaltyAmount: bigint,
      ) => ChainSubmittableExtrinsic<
        {
          pallet: 'Oracle';
          palletCall: {
            name: 'ConfirmCardanoWithdrawal';
            params: {
              txHash: FixedBytes<32>;
              releasedAmount: bigint;
              penaltyAmount: bigint;
            };
          };
        },
        ChainKnownTypes
      >
    >;

    /**
     * Generic pallet tx call
     **/
    [callName: string]: GenericTxCall<TxCall<ChainKnownTypes>>;
  };
}
